# Only overrides; everything else uses SearXNG's defaults.
use_default_settings: true

server:
  secret_key: "fdac84a79e93c4e66415ffa754339dfab3caf0b59c0a4ff81ecd812962065ac6"
  limiter: false

search:
  # json is required for Open WebUI's web search
  formats:
    - html
    - json
